tform/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.form_list, name='form_list'),
    path('form/new', views.form_new, name='form_new'),
    path('form/<int:id>', views.form_view, name='form_view'),
    path('form/<int:id>/delete', views.form_delete, name='form_delete'),
    path('form/<int:id>/publish', views.form_publish, name='form_publish'),
    path('form/<int:id>/response', views.response_list, name='response_list'),
    path('form/<int:id>/response/download', views.response_download, name='response_download'),
    path('form/<int:form_id>/response/<int:id>', views.response_view, name='response_view'),
    path('form/<int:id>/edit', views.form_edit, name='form_edit'),
    path('form/<int:id>/textfield/new', views.textfield_new, name='textfield_new'),
    path('form/<int:form_id>/textfield/<int:id>/edit', views.textfield_edit, name='textfield_edit'),
    path('form/<int:form_id>/textfield/<int:id>/delete', views.textfield_delete, name='textfield_delete'),
    path('form/<int:id>/mcqfield/new', views.mcqfield_new, name='mcqfield_new'),
    path('form/<int:form_id>/mcqfield/<int:id>/edit', views.mcqfield_edit, name='mcqfield_edit'),
    path('form/<int:form_id>/mcqfield/<int:id>/delete', views.mcqfield_delete, name='mcqfield_delete'),
    path('signup/', views.signup, name='signup'),
]

typeform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

def raise_zero_division_error(request):
    division_by_zero = 1 / 0

def raise_overflow_error(request):
    raise OverflowError('Result too large to be represented')

def raise_floating_point_error(request):
    raise FloatingPointError('Floating point operation failed')

def raise_attribute_error(request):
    raise AttributeError('Attribute not found')

def raise_import_error(request):
    raise ImportError("Import can't find module, or can't find name in module")

def raise_index_error(request):
    raise IndexError('Sequence index out of range')

def raise_key_error(request):
    raise KeyError('Mapping key not found')

def raise_name_error(request):
    raise NameError('Name not found globally')

def raise_type_error(request):
    raise TypeError('Inappropriate argument type')

def raise_value_error(request):
    raise ValueError('Inappropriate argument value (of correct type)')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('zero-division-error/', raise_zero_division_error),
    path('floating-point-error/', raise_floating_point_error),
    path('attribute-error/', raise_attribute_error),
    path('import-error/', raise_import_error),
    path('index-error/', raise_index_error),
    path('key-error/', raise_key_error),
    path('name-error/', raise_name_error),
    path('type-error/', raise_type_error),
    path('value-error/', raise_value_error),
    path('', include('tform.urls'))
]

tform/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from itertools import chain

# Create your models here.

class Form(models.Model):
    title = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    published_on = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)

    def publish(self):
        self.published_on = timezone.now()
        self.save()

    def get_order(self):
       text_field_count = len(self.textfield_set.all())
       mcq_field_count = len(self.mcqfield_set.all())
       return text_field_count + mcq_field_count

    def get_fields(self):
        text_fields = self.textfield_set.all()
        mcq_fields = self.mcqfield_set.all()
        fields = chain(text_fields, mcq_fields)
        return sorted(fields, key=lambda x: x.order)

    def __str__(self):
        return f"{self.title}"

class FormResponse(models.Model):
    submitted_on = models.DateTimeField(auto_now_add=True)
    form = models.ForeignKey(Form, models.CASCADE)

class TextField(models.Model):
    question = models.TextField()
    order = models.IntegerField()
    form = models.ForeignKey(Form, models.CASCADE)

    def __str__(self):
        return f"(Q: {self.question}) (O :{self.order})"

class TextFieldResponse(models.Model):
    response = models.TextField()
    text_field = models.ForeignKey(TextField, models.CASCADE)
    form_response = models.ForeignKey(FormResponse, models.CASCADE)

    def __str__(self):
        return f"{self.response}"

class McqField(models.Model):
    question = models.TextField()
    order = models.IntegerField()
    form = models.ForeignKey(Form, models.CASCADE)

    def __str__(self):
        return f"(Q: {self.question}) (O :{self.order})"

class McqChoiceField(models.Model):
    text = models.CharField(max_length=100)
    mcq_field = models.ForeignKey(McqField, models.CASCADE)

    def __str__(self):
        return f"{self.text}"

class McqFieldResponse(models.Model):
    mcq_choice_field = models.ForeignKey(McqChoiceField, models.CASCADE)
    mcq_field = models.ForeignKey(McqField, models.CASCADE)
    form_response = models.ForeignKey(FormResponse, models.CASCADE)

    def __str__(self):
        return f"{self.mcq_choice_field}"

tform/forms.py
from django.forms import ModelForm, CharField
from .models import Form, TextField, McqField, McqChoiceField

class TFormForm(ModelForm):
    class Meta:
        model = Form
        fields = ['title']


class TextFieldForm(ModelForm):
    class Meta:
        model = TextField
        fields = ['question']


class McqFieldForm(ModelForm):
    class Meta:
        model = McqField
        fields = ['question']

class McqChoiceFieldForm(ModelForm):
    class Meta:
        model = McqChoiceField
        fields = ['text']

tform/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from .models import Form, TextField, McqField, McqChoiceField, TextFieldResponse, McqFieldResponse, FormResponse
from .forms import TFormForm, TextFieldForm, McqFieldForm, McqChoiceFieldForm
import json, csv

# Create your views here.

@login_required
def form_list(request):
    forms = Form.objects.filter(user=request.user)
    return render(request, 'tform/form_list.html', {'forms': forms})


def form_view(request, id):
    form = get_object_or_404(Form.objects.prefetch_related(), pk=id)
    if (not form.published_on and (request.user != form.user)):
        raise PermissionDenied
    fields = form.get_fields()
    if request.method == 'POST':
        form_response = FormResponse.objects.create(form=form)
        for form_data_field in request.POST:
            form_data_field_slug = form_data_field.split('-')
            form_data_field_type = form_data_field_slug[0]
            if len(form_data_field_slug) == 2:
                form_data_field_id = form_data_field_slug[1]
            form_data_field_value = request.POST.get(form_data_field)
            if (form_data_field_type == 'text'):
                text_field_response = TextFieldResponse.objects.create(response=form_data_field_value, text_field=TextField.objects.get(pk=form_data_field_id), form_response=form_response)
            if (form_data_field_type == 'mcq'):
                mcq_field_response = McqFieldResponse.objects.create(mcq_choice_field=McqChoiceField.objects.get(pk=form_data_field_value), mcq_field=McqField.objects.get(pk=form_data_field_id), form_response=form_response)
    return render(request, 'tform/form_view.html', {'form': form, 'fields': fields})


@login_required
def form_delete(request, id):
    form = get_object_or_404(Form, pk=id)
    if form.user != request.user:
        raise PermissionDenied
    form.delete()
    return redirect('form_list')


@login_required
def form_publish(request, id):
    form = get_object_or_404(Form.objects.prefetch_related(), pk=id)
    if form.user != request.user:
        raise PermissionDenied
    form.publish()
    return redirect('form_view', id=form.pk)

@login_required
def form_new(request):
    if request.method == 'POST':
        form = TFormForm(request.POST)
        if form.is_valid():
            tform = form.save(commit=False)
            tform.user = request.user
            tform.save()
            return redirect('form_list')
    else:
        form = TFormForm()
    return render(request, 'tform/form_new.html', {'form': form})


@login_required
def form_edit(request, id):
    form = get_object_or_404(Form.objects.prefetch_related('textfield_set', 'mcqfield_set'), pk=id)
    if form.user != request.user:
        raise PermissionDenied
    form_fields = form.get_fields()
    return render(request, 'tform/form_edit.html', {'form': form, 'fields': form_fields})


@login_required
def textfield_new(request, id):
    tform = get_object_or_404(Form, pk=id)
    if tform.user != request.user:
        raise PermissionDenied
    if request.method == 'POST':
        form = TextFieldForm(request.POST)
        if form.is_valid():
            text_field = form.save(commit=False)
            text_field.order = tform.get_order() + 1
            text_field.form = tform
            text_field.save()
            return redirect('form_edit', id=tform.pk)
    else:
        form = TextFieldForm()
    return render(request, 'tform/textfield_edit.html', {'form': form, 'edit_mode': False})


@login_required
def mcqfield_new(request, id):
    tform = get_object_or_404(Form, pk=id)
    if tform.user != request.user:
        raise PermissionDenied
    McqChoiceFieldFormset = inlineformset_factory(McqField, McqChoiceField, fields=('text',), extra=1, can_delete=True)
    if request.method == 'POST':
        mcq_field_form = McqFieldForm(request.POST)
        formset = McqChoiceFieldFormset(request.POST)
        if mcq_field_form.is_valid():
            new_mcq_field = mcq_field_form.save(commit=False)
            new_mcq_field.form = tform
            new_mcq_field.order = tform.get_order() + 1
            formset = McqChoiceFieldFormset(request.POST, instance=new_mcq_field)

            if formset.is_valid():
                new_mcq_field.save()
                formset.save()
                return redirect('form_edit', id=tform.pk)
    else:
        mcq_field_form = McqFieldForm()
        formset = McqChoiceFieldFormset()
    return render(request, 'tform/mcqfield_edit.html', {'form': mcq_field_form, 'formset': formset})


@login_required
def textfield_edit(request, form_id, id):
    tform = get_object_or_404(Form, pk=form_id)
    if tform.user != request.user:
        raise PermissionDenied
    text_field = get_object_or_404(TextField, pk=id)
    if request.method == 'POST':
        form = TextFieldForm(request.POST, instance=text_field)
        if form.is_valid():
            form.save()
            return redirect('form_edit', id=tform.pk)
    else:
        form = TextFieldForm(instance=text_field)
    return render(request, 'tform/textfield_edit.html', {'form': form, 'edit_mode': True})


@login_required
def mcqfield_edit(request, form_id, id):
    tform = get_object_or_404(Form, pk=form_id)
    if tform.user != request.user:
        raise PermissionDenied
    mcq_field = get_object_or_404(McqField.objects.select_related(), pk=id)
    McqChoiceFieldFormset = inlineformset_factory(McqField, McqChoiceField, fields=('text',), extra=0, can_delete=True)
    if request.method == 'POST':
        mcq_field_form = McqFieldForm(request.POST, instance=mcq_field)
        formset = McqChoiceFieldFormset(request.POST, instance=mcq_field)
        if mcq_field_form.is_valid():
            if formset.is_valid():
                updated_mcq_field = mcq_field_form.save()
                formset.save()
                return redirect('form_edit', id=tform.pk)
    else:
        mcq_field_form = McqFieldForm(instance=mcq_field)
        formset = McqChoiceFieldFormset(instance=mcq_field)
    return render(request, 'tform/mcqfield_edit.html', {'form': mcq_field_form, 'formset': formset})


@login_required
def textfield_delete(request, form_id, id):
    form = get_object_or_404(Form, pk=form_id)
    if form.user != request.user:
        raise PermissionDenied
    text_field = get_object_or_404(TextField, pk=id)
    if form.user == request.user:
        text_field.delete()
    return redirect('form_edit', id=form.pk)


@login_required
def mcqfield_delete(request, form_id, id):
    form = get_object_or_404(Form, pk=form_id)
    if form.user != request.user:
        raise PermissionDenied
    mcq_field = get_object_or_404(McqField, pk=id)
    if form.user == request.user:
        mcq_field.delete()
    return redirect('form_edit', id=form.pk)


@login_required
def response_list(request, id):
    form = get_object_or_404(Form.objects.prefetch_related(), pk=id)
    if form.user != request.user:
        raise PermissionDenied
    responses = form.formresponse_set.all()
    return render(request, 'tform/response_list.html', {'form': form, 'responses': responses})


@login_required
def response_view(request, form_id, id):
    form = get_object_or_404(Form.objects.prefetch_related(), pk=form_id)
    if form.user != request.user:
        raise PermissionDenied
    form_response = get_object_or_404(FormResponse.objects.prefetch_related(), pk=id)
    fields = form.get_fields()
    return render(request, 'tform/response_view.html', {'form': form, 'fields': fields, 'response': form_response})


@login_required
def response_download(request, id):
    form = get_object_or_404(Form.objects.prefetch_related(), pk=id)
    if form.user != request.user:
        raise PermissionDenied
    form_responses = form.formresponse_set.all()
    if len(form_responses) == 0:
        return redirect('response_list', id=form.pk)
    form_fields = form.get_fields()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f"attachment; filename='{form.title}-responses.csv'"
    writer = csv.writer(response)
    writer.writerow([field.question for field in form_fields])
    for form_response in form_responses:
        responses = []
        for field in form_fields:
            if type(field) is TextField:
                text_field_response = TextFieldResponse.objects.filter(form_response=form_response, text_field=field).first()
                if text_field_response:
                    responses.append(text_field_response.response)
            if type(field) is McqField:
                mcq_field_response = McqFieldResponse.objects.filter(form_response=form_response, mcq_field=field).first()
                if mcq_field_response:
                    responses.append(mcq_field_response.mcq_choice_field)
        writer.writerow(responses)
    return response


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('form_list')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

tform/templates/tform/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Typeform Clone</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container mb-5">
      <div class="row justify-content-center py-3">
        <div class="col-6">
          <nav class="nav d-flex justify-content-between">
            <div class="nav__item">
              <a href="{% url 'form_list' %}">Home</a>
            </div>
            {% if user.is_authenticated %}
              <div class="nav__item">
                <a href="{% url 'form_new' %}">Create Form</a>
              </div>
              <div class="nav__item"><a href="{% url 'logout' %}">Logout</a></div>
            {% else %}
              <div class="nav__item"><a href="{% url 'login' %}">Login</a></div>
              <div class="nav__item"><a href="{% url 'signup' %}">Signup</a></div>
            {% endif %}
          </nav>
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

tform/templates/tform/form_edit.html
{% extends './base.html' %}
{% load field_type %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="col-12 text-center mb-3">
                    <h2>{{ form.title }}</h2>
                </div>
                <div class="col-12" id="field__container">
                    {% for field in fields %}
                        {% if field|field_type == 'TextField' %}
                            <div class="field py-2 px-4 mb-3 d-flex" data-type="text_field">
                                <div class="field__header mr-3">
                                    <div class="field__order">{{ field.order }}</div>
                                </div>
                                <div class="field__body">
                                    <div class="field__question mb-2">{{ field.question }}</div>
                                    <div class="field__footer">
                                        <a href="{% url 'textfield_delete' form_id=form.pk id=field.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
                                        <a href="{% url 'textfield_edit' form_id=form.pk id=field.pk %}" class="btn btn-sm btn-outline-dark">Edit</a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="field py-2 px-4 mb-3 d-flex" data-type="mcq_field">
                                <div class="field__header mr-3">
                                    <div class="field__order">{{ field.order }}</div>
                                </div>
                                <div class="field__body">
                                    <div class="field__question mb-2">{{ field.question }}</div>
                                    <div class="field__options">
                                        {% for choice in field.mcqchoicefield_set.all %}
                                            <div class="field__option mb-1">- {{ choice.text }}</div>
                                        {% endfor %}
                                    </div>
                                    <div class="field__footer">
                                        <a href="{% url 'mcqfield_delete' form_id=form.pk id=field.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
                                        <a href="{% url 'mcqfield_edit' form_id=form.pk id=field.pk %}" class="btn btn-sm btn-outline-dark">Edit</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-12 d-flex justify-content-center mb-3">
                    <a href="{% url 'textfield_new' id=form.id %}" class="btn btn-outline-dark mr-3">Add Text Field</a>
                    <a href="{% url 'mcqfield_new' id=form.id %}" class="btn btn-outline-dark">Add MCQ Field</a>
                </div>
                <div class="col-12 d-flex justify-content-center">
                    <a href="{% url 'response_list' id=form.pk %}" class="btn btn-outline-dark mr-3">Responses</a>
                    <a href="{% url 'form_publish' id=form.pk %}" class="btn btn-outline-dark">Publish</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tform/templates/tform/form_list.html
{% extends './base.html' %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            {% for form in forms %}
                <div class="col-12 col-sm-4 col-md-3 d-flex justify-content-center align-items-center">
                    <a href="{% url 'form_edit' id=form.id %}">
                        <div class="tform d-flex flex-column">
                            <div class="tform__header d-flex justify-content-center align-items-center">
                                {{ form.title }}
                            </div>
                            <div class="tform__footer py-2 d-flex justify-content-center">
                                <a href="{% url 'form_delete' id=form.pk %}" class="btn btn-sm btn-outline-danger mr-3">Delete</a>
                                <a href="{% url 'form_view' id=form.pk %}" class="btn btn-sm btn-outline-dark">View</a>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

tform/templates/tform/form_new.html
{% extends './base.html' %}
{% block content %}
    <div class="container d-flex flex-column justify-content-center align-items-center h-fluid-wrapper">
        <div class="row">
            <div class="col-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {% if form.title.errors %}
                            <label for="" class="form-text">Enter Typeform Name</label>
                            <input type="text" name="{{ form.title.html_name }}" class="form-control is-invalid">
                            {% for error in form.title.errors %}
                                <div class="error mt-2">{{ error }}</div>
                            {% endfor %}
                        {% else %}
                            <label for="" class="form-text">Enter Typeform Name</label>
                            <input type="text" name="{{ form.title.html_name }}" class="form-control">
                        {% endif %}
                    </div>
                    <button type="submit" class=" btn btn-block btn-outline-primary">Create Typeform</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tform/templates/tform/form_view.html
{% extends './base.html' %}
{% load field_type %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-6">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="col-12" id="field__container">
                        {% for field in fields %}
                            {% if field|field_type == 'TextField' %}
                                <div class="field py-2 px-4 mb-3 d-flex" data-type="text_field" data-id="{{ field.pk }}">
                                    <!-- <div class="field__header mr-3">
                                        <div class="field__order">{{ field.order }}</div>
                                    </div> -->
                                    <div class="field__body">
                                        <div class="field__question mb-2">{{ field.question }}</div>
                                        <input type="text" name="text-{{ field.pk }}" id="" class="form-control" required>
                                    </div>
                                </div>
                            {% else %}
                                <div class="field py-2 px-4 mb-3 d-flex" data-type="mcq_field" data-id="{{ field.pk }}">
                                    <!-- <div class="field__header mr-3">
                                        <div class="field__order">{{ field.order }}</div>
                                    </div> -->
                                    <div class="field__body">
                                        <div class="field__question mb-2">{{ field.question }}</div>
                                        <div class="field__options">
                                            {% for choice in field.mcqchoicefield_set.all %}
                                                <div class="field__option mb-1">
                                                    <input type="radio" name="mcq-{{field.pk}}" class="form-check d-inline" value="{{ choice.id }}" required>
                                                    <label class="form-check-label" for="">{{ choice.text }}</label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-12 d-flex justify-content-center">
                        <button type="submit" id="submit__btn" class="btn btn-outline-dark">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tform/templates/tform/mcqfield_edit.html
{% extends './base.html' %}
{% block content %}
    <div class="container h-fluid-wrapper">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-6">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <div class="form-group">
                        {% if form.question.errors %}
                            <label for="" class="form-text">Type your question here...</label>
                            <input type="text" name="{{ form.question.html_name }}" class="form-control is-invalid" value="{{ form.question.value|default_if_none:'' }}">
                            {% for error in form.question.errors %}
                                <div class="error mt-2">{{ error }}</div>
                            {% endfor %}
                        {% else %}
                            <label for="" class="form-text">Type your question here...</label>
                            <input type="text" name="{{ form.question.html_name }}" class="form-control" value="{{ form.question.value|default_if_none:'' }}">
                        {% endif %}
                    </div>
                    <div class="col-12 px-0">
                        {% for form in formset %}
                            {{form.id}}
                            <div class="row formset_row">
                                <div class="col-8">
                                    <div class="form-group">
                                        {% if form.errors %}
                                            {{ form.DELETE }}
                                            <input type="text" name="{{form.text.html_name}}" placeholder="Choice" class="form-control is-invalid" value="{{ form.text.value|default_if_none:'' }}">
                                            {% for error in form.errors.id %}
                                                <div class="error mt-2">{{ error }}</div>
                                            {% endfor %}
                                        {% else %}
                                            {{ form.DELETE }}
                                            <input type="text" name="{{form.text.html_name}}" placeholder="Choice" class="form-control" value="{{ form.text.value|default_if_none:'' }}">
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <button type="submit" class=" btn btn-block btn-outline-dark mt-4">Create MCQ Field</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tform/templates/tform/response_list.html
{% extends './base.html' %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-6">
                {% for response in responses %}
                    <a href="{% url 'response_view' form_id=form.pk id=response.pk %}">
                        <div class="field col-12 mb-3 py-3 px-5">Response submitted on {{ response.submitted_on }}</div>
                    </a>
                {% endfor %}
                <a href="{% url 'response_download' id=form.pk %}" class="btn btn-block btn-outline-dark">Download All Responses</a>
            </div>
        </div>
    </div>
{% endblock %}

tform/templates/tform/response_view.html
{% extends './base.html' %}
{% load field_type get_response %}
{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-6">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="col-12" id="field__container">
                        {% for field in fields %}
                            {% if field|field_type == 'TextField' %}
                                <div class="field py-2 px-4 mb-3 d-flex" data-type="text_field" data-id="{{ field.pk }}">
                                    <!-- <div class="field__header mr-3">
                                        <div class="field__order">{{ field.order }}</div>
                                    </div> -->
                                    <div class="field__body">
                                        <div class="field__question mb-2">{{ field.question }}</div>
                                        <p>- {% get_response field.textfieldresponse_set %}</p>
                                    </div>
                                </div>
                            {% else %}
                                <div class="field py-2 px-4 mb-3 d-flex" data-type="mcq_field" data-id="{{ field.pk }}">
                                    <!-- <div class="field__header mr-3">
                                        <div class="field__order">{{ field.order }}</div>
                                    </div> -->
                                    <div class="field__body">
                                        <div class="field__question mb-2">{{ field.question }}</div>
                                        <div class="field__options">
                                            <p>- {% get_response field.mcqfieldresponse_set %}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}